version: "3"
services:
  cop-markov-twitter:
    container_name: cop-markov-twitter
    build: ./
    working_dir: ${PROJECT_DIR}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_TOKEN: ${TWITTER_TOKEN}
      TWITTER_TOKEN_SECRET: ${TWITTER_TOKEN_SECRET}
      PROJECT_DIR: ${PROJECT_DIR}
    volumes:
      - .:${PROJECT_DIR}:cached
      - ./entrypoint.sh:/entrypoint.sh
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /entrypoint.sh
    command: sleep infinity
