version: "3"
services:
  cop-markov-twitter:
    container_name: cop-markov-twitter
    build: ./
    working_dir: ${PWD}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_TOKEN: ${TWITTER_TOKEN}
      TWITTER_TOKEN_SECRET: ${TWITTER_TOKEN_SECRET}
      PROJECT_DIR: ${PWD}
    volumes:
      - .:${PWD}:cached
      - ./entrypoint.sh:/entrypoint.sh
      - cop-markov-pypoetry-cache:/root/.cache/pypoetry/
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /entrypoint.sh

volumes:
  cop-markov-pypoetry-cache:
